# docker-compose.yml
services:
  # Đặt tên cho service của chúng ta là 'api'
  api:
    # Build image từ Dockerfile trong thư mục hiện tại (.)
    build: .
    
    # Đặt tên cho container để dễ quản lý
    container_name: real_estate_api
    
    # Ánh xạ port: port 8000 trên máy host sẽ được chuyển tiếp đến port 8000 trong container
    ports:
      - "8000:8000"
      
    # Volume mounting: Đồng bộ hóa code giữa máy host và container
    # Giúp Uvicorn's --reload hoạt động. Mọi thay đổi trong code sẽ được cập nhật ngay lập tức
    # mà không cần build lại image.
    volumes:
      - ./app:/app/app
      - ./model_artifacts:/app/model_artifacts
      
    # Ghi đè CMD mặc định trong Dockerfile để bật chế độ --reload cho development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  trainer:
    build:
      context: .
      dockerfile: trainer.Dockerfile # <-- SỬ DỤNG DOCKERFILE MỚI
    container_name: model_trainer_tool
    volumes:
      # Mount thư mục model_artifacts vào thư mục làm việc của trainer
      # Để script có thể ghi kết quả ra máy host
      - ./model_artifacts:/trainer_app
      # Mount file dữ liệu để script có thể đọc
      - ./chotot_bds_video_data.csv:/trainer_app/chotot_bds_video_data.csv