# api/wrangler.toml
name = "api"
main = "src/main.ts"
compatibility_date = "2024-01-01"
node_compat = true

[vars]
ENVIRONMENT = "production"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./dist/main.js"
